<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tx_spt_ppn', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('formulir_id');
            $table->string('nama_ptkp_1111');
            $table->string('alamat_1111');
            $table->string('no_telp_1111');
            $table->string('no_hp_1111');
            $table->string('no_klu_1111');
            $table->string('no_npwp_1111');
            $table->dateTime('start_masa_1111');
            $table->dateTime('end_masa_1111');
            $table->dateTime('start_tahun_buku_1111');
            $table->dateTime('end_tahun_buku_1111');
            $table->integer('pembetulan_1111');
            $table->float('i_a_1_dpp_1111');
            $table->float('i_a_2_dpp_1111');
            $table->float('i_a_2_ppn_1111');
            $table->float('i_a_3_dpp_1111');
            $table->float('i_a_3_ppn_1111');
            $table->float('i_a_4_dpp_1111');
            $table->float('i_a_4_ppn_1111');
            $table->float('i_a_5_dpp_1111');
            $table->float('i_a_5_ppn_1111');
            $table->float('i_a_jumlah_dpp_1111');
            $table->float('i_a_jumlah_ppn_1111');
            $table->float('i_b_dpp_1111');
            $table->float('i_c_dpp_1111');
            $table->float('ii_a_ppn_1111');
            $table->float('ii_b_ppn_1111');
            $table->float('ii_c_ppn_1111');
            $table->float('ii_d_ppn_1111');
            $table->float('ii_e_ppn_1111');
            $table->float('ii_f_ppn_1111');
            $table->dateTime('ii_g_start_1111');
            $table->string('ii_g_ntpp_1111');
            $table->integer('ii_h_ppn_lebih_1111');
            $table->integer('ii_h_oleh_1111');
            $table->integer('ii_h_diminta_untuk_1111');
            $table->dateTime('ii_h_diminta_untuk_date_1111')->nullable();
            $table->integer('ii_h_restitusi_1111');
            $table->integer('ii_h_prosedur_1111')->nullable();
            $table->integer('iii_a_ppn_1111');
            $table->integer('iii_b_ppn_1111');
            $table->dateTime('iii_c_date_1111');
            $table->string('iii_c_ntpp_1111');
            $table->integer('iv_a_ppn_1111');
            $table->dateTime('iv_b_date_1111');
            $table->string('iv_b_ntpn_1111');
            $table->float('v_a_ppn_1111');
            $table->float('v_b_ppn_1111');
            $table->float('v_c_ppn_1111');
            $table->float('v_d_ppn_1111');
            $table->float('v_e_ppn_1111');
            $table->dateTime('v_f_date_1111');
            $table->float('v_f_ntpp_1111');
            $table->integer('vi_formulir_1111');
            $table->integer('vi_lembar_1111')->nullable();
            $table->string('vi_tempat_1111');
            $table->integer('vi_penandatangan_1111');
            $table->string('vi_nama_jelas_1111');
            $table->string('vi_jabatan_1111');
            $table->string('nama_pkp_1111_AB');
            $table->string('npwp_1111_AB');
            $table->dateTime('start_masa_1111_AB');
            $table->dateTime('end_masa_1111_AB');
            $table->string('pembetulan_1111_AB');
            $table->float('i_a_dpp_1111_AB');
            $table->float('i_b_1_dpp_1111_AB');
            $table->float('i_b_1_ppn_1111_AB');
            $table->float('i_b_1_ppnbm_1111_AB');
            $table->float('i_b_2_dpp_1111_AB');
            $table->float('i_b_2_ppn_1111_AB');
            $table->float('i_b_2_ppnbm_1111_AB');
            $table->float('i_c_1_dpp_1111_AB');
            $table->float('i_c_1_ppn_1111_AB');
            $table->float('i_c_1_ppnbm_1111_AB');
            $table->float('i_c_2_dpp_1111_AB');
            $table->float('i_c_2_ppn_1111_AB');
            $table->float('i_c_2_ppnbm_1111_AB');
            $table->float('i_c_3_dpp_1111_AB');
            $table->float('i_c_3_ppn_1111_AB');
            $table->float('i_c_3_ppnbm_1111_AB');
            $table->float('i_c_4_dpp_1111_AB');
            $table->float('i_c_4_ppn_1111_AB');
            $table->float('i_c_4_ppnbm_1111_AB');
            $table->float('ii_a_dpp_1111_AB');
            $table->float('ii_a_ppn_1111_AB');
            $table->float('ii_a_ppnbm_1111_AB');
            $table->float('ii_b_dpp_1111_AB');
            $table->float('ii_b_ppn_1111_AB');
            $table->float('ii_b_ppnbm_1111_AB');
            $table->float('ii_c_dpp_1111_AB');
            $table->float('ii_c_ppn_1111_AB');
            $table->float('ii_c_ppnbm_1111_AB');
            $table->float('ii_d_dpp_1111_AB');
            $table->float('ii_d_ppn_1111_AB');
            $table->float('ii_d_ppnbm_1111_AB');
            $table->float('iii_a_pajak_masuk_1111_AB');
            $table->float('iii_b_pajaksebelumnya_1111_AB');
            $table->dateTime('iii_b_spt_ppn_date_1111_AB');
            $table->float('iii_b_spt_ppn_1111_AB');
            $table->float('iii_b_pajak_masuk_1111_AB');
            $table->float('iii_b_jumlah_1111_AB');
            $table->float('iii_b_jumlah_pajak_masuk_1111_AB');
            $table->string('nama_pkp_1111_A1');
            $table->string('npwp_1111_A1');
            $table->dateTime('start_masa_1111_A1');
            $table->dateTime('end_masa_1111_A1');
            $table->string('pembetul_1111_A1');
            $table->float('jumlah_dpp_1111_A1');
            $table->string('nama_pkp_1111_A2');
            $table->string('npwp_1111_A2');
            $table->dateTime('start_masa_1111_A2');
            $table->dateTime('end_masa_1111_A2');
            $table->string('pembetul_1111_A2');
            $table->float('jumlah_dpp_1111_A2');
            $table->float('jumlah_ppn_1111_A2');
            $table->string('nama_pkp_1111_B1');
            $table->string('npwp_1111_B1');
            $table->dateTime('start_masa_1111_B1');
            $table->dateTime('end_masa_1111_B1');
            $table->string('pembetul_1111_B1');
            $table->float('jumlah_dpp_1111_B1');
            $table->float('jumlah_ppn_1111_B1');
            $table->float('jumlah_ppnbm_1111_B1');
            $table->string('nama_pkp_1111_B2');
            $table->string('npwp_1111_B2');
            $table->dateTime('start_masa_1111_B2');
            $table->dateTime('end_masa_1111_B2');
            $table->string('pembetul_1111_B2');
            $table->float('jumlah_dpp_1111_B2');
            $table->float('jumlah_ppn_1111_B2');
            $table->float('jumlah_ppnbm_1111_B2');
            $table->string('nama_pkp_1111_B3');
            $table->string('npwp_1111_B3');
            $table->dateTime('start_masa_1111_B3');
            $table->dateTime('end_masa_1111_B3');
            $table->string('pembetul_1111_B3');
            $table->float('jumlah_dpp_1111_B3');
            $table->float('jumlah_ppn_1111_B3');
            $table->float('jumlah_ppnbm_1111_B3');
            $table->string('attribute_1')->nullable();
            $table->string('attribute_2')->nullable();
            $table->string('attribute_3')->nullable();
            $table->timestamps();
            $table->dateTime('deleted_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tx_spt_ppn');
    }
};
