<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\User;
use App\Models\MasaBulan;
class SptMasa extends Model
{
    use HasFactory,SoftDeletes;
    public $table = 'tx_formulir_1721_head';
    protected $fillable = [
        'id',
        'formulir_id',
        'npwp',
        'nama',
        'ptkp',
        'alamat',
        'no_telp',
        'email',
        'alamat_objekpajak',
        'b1_penerima_penghasilan_1721',
        'b1_penghasilan_bruto_1721',
        'b1_jumlahpajak_1721',
        'b2_penerima_penghasilan_1721',
        'b2_penghasilan_bruto_1721',
        'b2_jumlahpajak_1721',
        'b3_penerima_penghasilan_1721',
        'b3_penghasilan_bruto_1721',
        'b3_jumlahpajak_1721',
        'b4a_penerima_penghasilan_1721',
        'b4a_penghasilan_bruto_1721',
        'b4a_jumlahpajak_1721',
        'b4b_penerima_penghasilan_1721',
        'b4b_penghasilan_bruto_1721',
        'b4b_jumlahpajak_1721',
        'b4c_penerima_penghasilan_1721',
        'b4c_penghasilan_bruto_1721',
        'b4c_jumlahpajak_1721',
        'b4d_penerima_penghasilan_1721',
        'b4d_penghasilan_bruto_1721',
        'b4d_jumlahpajak_1721',
        'b4e_penerima_penghasilan_1721',
        'b4e_penghasilan_bruto_1721',
        'b4e_jumlahpajak_1721',
        'b4f_penerima_penghasilan_1721',
        'b4f_penghasilan_bruto_1721',
        'b4f_jumlahpajak_1721',
        'b5_penerima_penghasilan_1721',
        'b5_penghasilan_bruto_1721',
        'b5_jumlahpajak_1721',
        'b6_penerima_penghasilan_1721',
        'b6_penghasilan_bruto_1721',
        'b6_jumlahpajak_1721',
        'b7_penerima_penghasilan_1721',
        'b7_penghasilan_bruto_1721',
        'b7_jumlahpajak_1721',
        'b8_penerima_penghasilan_1721',
        'b8_penghasilan_bruto_1721',
        'b8_jumlahpajak_1721',
        'b9_penerima_penghasilan_1721',
        'b9_penghasilan_bruto_1721',
        'b9_jumlahpajak_1721',
        'b10_penerima_penghasilan_1721',
        'b10_penghasilan_bruto_1721',
        'b10_jumlahpajak_1721',
        'b11_penerima_penghasilan_1721',
        'b11_penghasilan_bruto_1721',
        'b11_jumlahpajak_1721',
        'jumlah_penerima_penghasilan_b',
        'jumlah_penghasilan_bruto_b',
        'jumlah_pajak_dipotong_b',
        'pokok_pajak',
        'masa_pajak_bulan',
        'masa_pajak_tahun',
        'masa_pajak_pokok',
        'jumlah_objekpajak',
        'kurang_lebih_setor',
        'spt_dibetulkan',
        'spt_pembetulan',
        'kompensasi',
        'npwp_pemotong',
        'c1_penerima_penghasilan_1721',
        'c1_penghasilan_bruto_1721',
        'c1_jumlahpajak_1721',
        'c2_penerima_penghasilan_1721',
        'c2_penghasilan_bruto_1721',
        'c2_jumlahpajak_1721',
        'c3_penerima_penghasilan_1721',
        'c3_penghasilan_bruto_1721',
        'c3_jumlahpajak_1721',
        'c4_penerima_penghasilan_1721',
        'c4_penghasilan_bruto_1721',
        'c4_jumlahpajak_1721',
        'jumlah_penerima_penghasilan_c',
        'jumlah_penghasilan_bruto_c',
        'jumlah_pajak_dipotong_c',
        'lembar_formulir_1721I',
        'lembar_formulir_1721II',
        'lembar_formulir_1721III',
        'lembar_formulir_1721IV',
        'lembar_formulir_1721V',
        'surat_setoran_pajak',
        'surat_kuasa_khusus',
        'pernyataan_ttd',
        'npwp_ttd',
        'nama_ttd',
        'tanggal_ttd',
        'tempat_ttd',
        'attribute1',
        'attribute2',
        'attribute3',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
    public function users()
    {
        return $this->hasOne(User::class,'id','attribute1');
    }
    public function bulan()
    {
        return $this->hasOne(MasaBulan::class,'value','masa_pajak_bulan');
    }
}
